networks:
  main:


volumes:
  mysql:


services:
  backend:
    build:
      context: ../backend
      dockerfile: ../backend/docker/Dockerfile
    networks:
      - main
    ports:
      - 8081:8080
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/docker/Dockerfile
    ports:
      - 8082:80
    networks:
      - main
  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yugioh_db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
