name: Lint Backend
description: Lints the code in the backend so we can make sure to keep stuff looking consistent
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      shell: bash
      working-directory: ./backend
      run: pip install -r requirements-dev.txt

    - name: Run All Tests
      shell: bash
      working-directory: ./backend
      run: make lint
