#@ load("@ytt:data", "data")

#@ namespace = "yugioh-card-puller-{}".format(data.values.env)
#@ app = "yugioh-card-puller-backend-{}".format(data.values.env)

#@ env = data.values.env
#@ image = data.values.image
#@ port = 8080

#@ def labels():
  app: #@ app
#@ end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ namespace
  name: #@ "{}-deployment".format(app)
  labels: #@ labels()
spec:
  metadata:
    namespace: #@ namespace
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      namespace: #@ namespace
      labels: #@ labels()
    spec:
      containers:
        - name: fastapi-instance
          image: #@ "gxldcptrick/yugioh-card-backend:{}".format(image)
          env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: LOG_FORMAT
            value: json
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth0-yugioh
                key: auth0_client_id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth0-yugioh
                key: auth0_client_secret
          - name: APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth0-yugioh
                key: app_secret
