volumes:
  mysql:
  kuma:

networks:
  main:

services:
  backend:
    depends_on:
      - database
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - main
    ports:
      - 8081:8080
    expose:
      - 8080

  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - main

    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
  
  kuma:
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    networks:
      - main
    volumes:
      - kuma:/app/data
