"""adding relationships again

Revision ID: 04055eb8d7f2
Revises: a32ec2619c0c
Create Date: 2024-03-04 16:06:03.510528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04055eb8d7f2'
down_revision = 'a32ec2619c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
