"""Initial DB design

Revision ID: 4c80172f9355
Revises: 
Create Date: 2023-08-02 13:56:52.707567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c80172f9355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yugioh_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('archetype', sa.String(length=255), nullable=True),
    sa.Column('race', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yugioh_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yugioh_card_set_associations',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('rarity', sa.String(length=255), nullable=False),
    sa.Column('rarity_code', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['yugioh_cards.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['yugioh_sets.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yugioh_card_set_associations')
    op.drop_table('yugioh_sets')
    op.drop_table('yugioh_cards')
    # ### end Alembic commands ###
