name: Test Backend
description: Validates the Backend codebase
runs:
  using: composite
  steps:
    - name: Go into Backend
      shell: bash
      run: cd Backend

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.0"

    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements-dev.txt

    - name: Run All Tests
      shell: bash
      run: pytest tests
