name: Test Backend
description: Validates the Backend codebase
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      shell: bash
      working-directory: ./backend
      run: pip install -r requirements-dev.txt

    - name: Run All Tests
      shell: bash
      working-directory: ./backend
      run: pytest tests
