name: Merge Backend Workflow
on:
  push:
    paths:
      - "backend/**/*"
    branches:
      - main
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-backend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint-backend
