name: Pull Request Workflow
on:
    pull_request:
        branches:
            - main
jobs:
    test-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/test-backend
    test-web-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/test-web-frontend
    test-mobile-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/test-mobile-frontend
              env:
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true